In [ ]:
# Задание:

#     Загрузите данные, проверьте правильность, наличие пропущенных значений, типы данных.
    
#     Создайте новый признак – марку автомобиля (company). Машины каких производителей встречаются в датасете? 
#     Далее исправьте названия и проверьте изменения.
    
#     Оставьте только часть предикторов, после чего посчитайте корреляцию между price и другими переменными.
    
#     Преобразуйте категориальные переменные с помощью pd.get_dummies(). 
    
#     Постройте модель с одним предиктором цены – horsepower. Какой процент изменчивости объясняет 
#     полученная модель? (\(R^2\))
    
#     Далее – две модели (со всеми предикторами и со всеми, кроме марок машин). Обратите внимание на 
#     изменения в \(R^2\), коэффициентах и их значимости. Какую модель лучше оставить? 
    
#     Заполните пропуски в результатах.

In [ ]:
#     Загрузите данные, проверьте правильность, наличие пропущенных значений, типы данных.

In [197]:
import pandas as pd
import statsmodels.formula.api as smf
import statsmodels.api as sm

In [147]:
cars = pd.read_csv('cars.csv')
cars

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,1,3,alfa-romero giulia,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.0
1,2,3,alfa-romero stelvio,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.0
2,3,1,alfa-romero Quadrifoglio,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.0
3,4,2,audi 100 ls,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950.0
4,5,2,audi 100ls,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,201,-1,volvo 145e (sw),gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845.0
201,202,-1,volvo 144ea,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045.0
202,203,-1,volvo 244dl,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485.0
203,204,-1,volvo 246,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106,4800,26,27,22470.0
204,205,-1,volvo 264gl,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625.0

In [148]:
cars.dtypes

car_ID                int64
symboling             int64
CarName              object
fueltype             object
aspiration           object
doornumber           object
carbody              object
drivewheel           object
enginelocation       object
wheelbase           float64
carlength           float64
carwidth            float64
carheight           float64
curbweight            int64
enginetype           object
cylindernumber       object
enginesize            int64
fuelsystem           object
boreratio           float64
stroke              float64
compressionratio    float64
horsepower            int64
peakrpm               int64
citympg               int64
highwaympg            int64
price               float64
dtype: object

In [149]:
cars.isna().sum()

car_ID              0
symboling           0
CarName             0
fueltype            0
aspiration          0
doornumber          0
carbody             0
drivewheel          0
enginelocation      0
wheelbase           0
carlength           0
carwidth            0
carheight           0
curbweight          0
enginetype          0
cylindernumber      0
enginesize          0
fuelsystem          0
boreratio           0
stroke              0
compressionratio    0
horsepower          0
peakrpm             0
citympg             0
highwaympg          0
price               0
dtype: int64

In [ ]:
#     Создайте новый признак – марку автомобиля (company). Машины каких производителей встречаются в датасете? 
#     Далее исправьте названия и проверьте изменения.

In [150]:
cars['company'] = cars.CarName.apply(lambda x: x.split()[0])

In [151]:
cars = cars.drop(['CarName', 'car_ID'], axis=1)

In [152]:
cars

,symboling,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,carlength,carwidth,...,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price,company
0,3,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,...,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.0,alfa-romero
1,3,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,...,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.0,alfa-romero
2,1,gas,std,two,hatchback,rwd,front,94.5,171.2,65.5,...,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.0,alfa-romero
3,2,gas,std,four,sedan,fwd,front,99.8,176.6,66.2,...,mpfi,3.19,3.40,10.0,102,5500,24,30,13950.0,audi
4,2,gas,std,four,sedan,4wd,front,99.4,176.6,66.4,...,mpfi,3.19,3.40,8.0,115,5500,18,22,17450.0,audi
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,gas,std,four,sedan,rwd,front,109.1,188.8,68.9,...,mpfi,3.78,3.15,9.5,114,5400,23,28,16845.0,volvo
201,-1,gas,turbo,four,sedan,rwd,front,109.1,188.8,68.8,...,mpfi,3.78,3.15,8.7,160,5300,19,25,19045.0,volvo
202,-1,gas,std,four,sedan,rwd,front,109.1,188.8,68.9,...,mpfi,3.58,2.87,8.8,134,5500,18,23,21485.0,volvo
203,-1,diesel,turbo,four,sedan,rwd,front,109.1,188.8,68.9,...,idi,3.01,3.40,23.0,106,4800,26,27,22470.0,volvo
204,-1,gas,turbo,four,sedan,rwd,front,109.1,188.8,68.9,...,mpfi,3.78,3.15,9.5,114,5400,19,25,22625.0,volvo

In [153]:
cars.company.nunique()

28

In [154]:
cars.company.value_counts()

toyota         31
nissan         17
mazda          15
honda          13
mitsubishi     13
subaru         12
peugeot        11
volvo          11
volkswagen      9
dodge           9
buick           8
bmw             8
audi            7
plymouth        7
saab            6
isuzu           4
porsche         4
alfa-romero     3
chevrolet       3
jaguar          3
vw              2
maxda           2
renault         2
toyouta         1
vokswagen       1
Nissan          1
mercury         1
porcshce        1
Name: company, dtype: int64

In [101]:
# cars.company.apply(lambda x: x.lower()) \
#     .apply(lambda x: x.replace('maxda', 'mazda')) \
#     .apply(lambda x: x.replace('toyouta', 'toyota')) \
#     .apply(lambda x: x.replace('vokswagen', 'volkswagen')) \
#     .apply(lambda x: x.replace('vw', 'volkswagen')) \
#     .apply(lambda x: x.replace('porcshce', 'porsche')) \
#     .nunique()

22

In [173]:
cars['company'] = cars.company.str.lower() \
    .replace('maxda', 'mazda') \
    .replace('toyouta', 'toyota') \
    .replace('vokswagen', 'volkswagen') \
    .replace('vw', 'volkswagen') \
    .replace('porcshce', 'porsche')

In [174]:
cars.company.nunique()

22

In [ ]:
#     Оставьте только часть предикторов, после чего посчитайте корреляцию между price и другими переменными.

In [177]:
cars[['company', 'fueltype', 'aspiration','carbody', 'drivewheel', 'wheelbase', 'carlength','carwidth', 
      'curbweight', 'enginetype', 'cylindernumber', 'enginesize', 'boreratio','horsepower', 'price']].corr() \
    .round(2)

,wheelbase,carlength,carwidth,curbweight,enginesize,boreratio,horsepower,price
wheelbase,1.00,0.87,0.80,0.78,0.57,0.49,0.35,0.58
carlength,0.87,1.00,0.84,0.88,0.68,0.61,0.55,0.68
carwidth,0.80,0.84,1.00,0.87,0.74,0.56,0.64,0.76
curbweight,0.78,0.88,0.87,1.00,0.85,0.65,0.75,0.84
enginesize,0.57,0.68,0.74,0.85,1.00,0.58,0.81,0.87
boreratio,0.49,0.61,0.56,0.65,0.58,1.00,0.57,0.55
horsepower,0.35,0.55,0.64,0.75,0.81,0.57,1.00,0.81
price,0.58,0.68,0.76,0.84,0.87,0.55,0.81,1.00

In [ ]:
#     Преобразуйте категориальные переменные с помощью pd.get_dummies().

In [178]:
cars.dtypes.sort_values()

symboling             int64
highwaympg            int64
citympg               int64
peakrpm               int64
horsepower            int64
curbweight            int64
enginesize            int64
compressionratio    float64
stroke              float64
wheelbase           float64
carlength           float64
carwidth            float64
carheight           float64
price               float64
boreratio           float64
enginetype           object
cylindernumber       object
enginelocation       object
drivewheel           object
carbody              object
doornumber           object
aspiration           object
fueltype             object
fuelsystem           object
company              object
dtype: object

In [179]:
df_dummy = pd.get_dummies(data=cars[['enginetype', 'cylindernumber', 'enginelocation', 'drivewheel', 'carbody',
                                     'doornumber', 'aspiration', 'fueltype' , 'fuelsystem', 'company']], drop_first = True)

In [180]:
df_dummy

,enginetype_dohcv,enginetype_l,enginetype_ohc,enginetype_ohcf,enginetype_ohcv,enginetype_rotor,cylindernumber_five,cylindernumber_four,cylindernumber_six,cylindernumber_three,...,company_nissan,company_peugeot,company_plymouth,company_porsche,company_renault,company_saab,company_subaru,company_toyota,company_volkswagen,company_volvo
0,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,1,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,1,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,1,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,0,0,1,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
201,0,0,1,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
202,0,0,0,0,1,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,1
203,0,0,1,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,1
204,0,0,1,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1

In [231]:
df_dummy_2 = pd.get_dummies(data=cars[['company', 'fueltype', 'aspiration','carbody', 'drivewheel', 
                                       'wheelbase', 'carlength','carwidth', 'curbweight', 'enginetype', 
                                       'cylindernumber', 'enginesize', 'boreratio','horsepower', 'price']], drop_first = True)

In [232]:
df_dummy_2

,wheelbase,carlength,carwidth,curbweight,enginesize,boreratio,horsepower,price,company_audi,company_bmw,...,enginetype_ohc,enginetype_ohcf,enginetype_ohcv,enginetype_rotor,cylindernumber_five,cylindernumber_four,cylindernumber_six,cylindernumber_three,cylindernumber_twelve,cylindernumber_two
0,88.6,168.8,64.1,2548,130,3.47,111,13495.0,0,0,...,0,0,0,0,0,1,0,0,0,0
1,88.6,168.8,64.1,2548,130,3.47,111,16500.0,0,0,...,0,0,0,0,0,1,0,0,0,0
2,94.5,171.2,65.5,2823,152,2.68,154,16500.0,0,0,...,0,0,1,0,0,0,1,0,0,0
3,99.8,176.6,66.2,2337,109,3.19,102,13950.0,1,0,...,1,0,0,0,0,1,0,0,0,0
4,99.4,176.6,66.4,2824,136,3.19,115,17450.0,1,0,...,1,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,109.1,188.8,68.9,2952,141,3.78,114,16845.0,0,0,...,1,0,0,0,0,1,0,0,0,0
201,109.1,188.8,68.8,3049,141,3.78,160,19045.0,0,0,...,1,0,0,0,0,1,0,0,0,0
202,109.1,188.8,68.9,3012,173,3.58,134,21485.0,0,0,...,0,0,1,0,0,0,1,0,0,0
203,109.1,188.8,68.9,3217,145,3.01,106,22470.0,0,0,...,1,0,0,0,0,0,1,0,0,0
204,109.1,188.8,68.9,3062,141,3.78,114,22625.0,0,0,...,1,0,0,0,0,1,0,0,0,0

In [ ]:
#     Постройте модель с одним предиктором цены – horsepower. Какой процент изменчивости объясняет 
#     полученная модель? (\(R^2\))

In [233]:
model_one = smf.ols('price ~ horsepower', df_dummy_2).fit().summary()
print(model_one)

                            OLS Regression Results
==============================================================================
Dep. Variable:                  price   R-squared:                       0.653
Model:                            OLS   Adj. R-squared:                  0.651
Method:                 Least Squares   F-statistic:                     382.2
Date:                Fri, 09 Dec 2022   Prob (F-statistic):           1.48e-48
Time:                        20:45:43   Log-Likelihood:                -2024.0
No. Observations:                 205   AIC:                             4052.
Df Residuals:                     203   BIC:                             4059.
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept  -3721.7615    929.849     -4.003      0.000   -5555.163   -1888.360
horsepower   163.2631      8.351     19.549      0.000     146.796     179.730
==============================================================================
Omnibus:                       47.741   Durbin-Watson:                   0.792
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               91.702
Skew:                           1.141   Prob(JB):                     1.22e-20
Kurtosis:                       5.352   Cond. No.                         314.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [ ]:
R-squared: 0.653 # 65%

In [ ]:
#     Далее – две модели (со всеми предикторами и со всеми, кроме марок машин). Обратите внимание на 
#     изменения в \(R^2\), коэффициентах и их значимости. Какую модель лучше оставить?

In [234]:
X1 = sm.add_constant(df_dummy_2.drop('price', axis=1))  #  модель со всеми предиктами

In [235]:
model_all = sm.OLS(df_dummy_2.price, X1).fit().summary()
print(model_all)

                            OLS Regression Results
==============================================================================
Dep. Variable:                  price   R-squared:                       0.959
Model:                            OLS   Adj. R-squared:                  0.948
Method:                 Least Squares   F-statistic:                     81.09
Date:                Fri, 09 Dec 2022   Prob (F-statistic):           4.86e-89
Time:                        20:45:48   Log-Likelihood:                -1804.2
No. Observations:                 205   AIC:                             3702.
Df Residuals:                     158   BIC:                             3858.
Df Model:                          46
Covariance Type:            nonrobust
=========================================================================================
                            coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------------
const                 -3.472e+04   1.17e+04     -2.959      0.004   -5.79e+04   -1.15e+04
wheelbase               147.1396     76.234      1.930      0.055      -3.429     297.708
carlength              -113.2012     48.949     -2.313      0.022    -209.881     -16.522
carwidth                809.1860    214.508      3.772      0.000     385.514    1232.858
curbweight                4.1822      1.582      2.643      0.009       1.057       7.307
enginesize               61.4212     23.643      2.598      0.010      14.724     108.119
boreratio             -4319.4728   1759.825     -2.454      0.015   -7795.288    -843.657
horsepower               34.7010     18.000      1.928      0.056      -0.850      70.252
company_audi            437.1040   2125.971      0.206      0.837   -3761.885    4636.093
company_bmw            7993.4998   2105.132      3.797      0.000    3835.671    1.22e+04
company_buick          3431.0969   2472.252      1.388      0.167   -1451.829    8314.023
company_chevrolet     -2107.0167   2054.269     -1.026      0.307   -6164.387    1950.353
company_dodge         -3034.5530   1686.337     -1.799      0.074   -6365.224     296.118
company_honda         -2328.7396   1622.141     -1.436      0.153   -5532.617     875.138
company_isuzu          -926.1643   1819.489     -0.509      0.611   -4519.823    2667.495
company_jaguar         2695.2664   2546.268      1.059      0.291   -2333.847    7724.379
company_mazda         -1291.5657   1652.561     -0.782      0.436   -4555.527    1972.395
company_mercury       -2762.0259   2786.701     -0.991      0.323   -8266.016    2741.965
company_mitsubishi    -3699.6473   1650.046     -2.242      0.026   -6958.640    -440.654
company_nissan        -1488.1217   1563.564     -0.952      0.343   -4576.305    1600.061
company_peugeot       -2671.4595   1795.328     -1.488      0.139   -6217.398     874.479
company_plymouth      -3052.1258   1670.829     -1.827      0.070   -6352.166     247.915
company_porsche        4915.9715   2797.761      1.757      0.081    -609.864    1.04e+04
company_renault       -2865.2197   2073.046     -1.382      0.169   -6959.676    1229.237
company_saab            719.8222   1767.620      0.407      0.684   -2771.390    4211.035
company_subaru        -1.164e+04   3416.221     -3.407      0.001   -1.84e+04   -4892.375
company_toyota        -2608.7871   1539.320     -1.695      0.092   -5649.086     431.512
company_volkswagen    -2261.9355   1606.886     -1.408      0.161   -5435.683     911.812
company_volvo            68.2605   1943.170      0.035      0.972   -3769.679    3906.200
fueltype_gas           -243.7792    908.310     -0.268      0.789   -2037.774    1550.216
aspiration_turbo        596.6566    676.548      0.882      0.379    -739.588    1932.902
carbody_hardtop       -2556.7157   1213.929     -2.106      0.037   -4954.337    -159.094
carbody_hatchback     -3044.4196   1107.064     -2.750      0.007   -5230.972    -857.867
carbody_sedan         -2256.9173   1154.971     -1.954      0.052   -4538.090      24.256
carbody_wagon         -2815.4970   1223.156     -2.302      0.023   -5231.343    -399.651
drivewheel_fwd         -169.4926    888.585     -0.191      0.849   -1924.531    1585.545
drivewheel_rwd          231.9066   1039.685      0.223      0.824   -1821.566    2285.380
enginetype_dohcv      -8358.0756   4326.239     -1.932      0.055   -1.69e+04     186.645
enginetype_l          -1067.3120   1602.125     -0.666      0.506   -4231.657    2097.033
enginetype_ohc         -273.7175   1063.557     -0.257      0.797   -2374.341    1826.906
enginetype_ohcf        1.031e+04   2672.508      3.857      0.000    5028.873    1.56e+04
enginetype_ohcv       -2393.8587   1214.631     -1.971      0.050   -4792.867       5.150
enginetype_rotor         37.4715   2092.597      0.018      0.986   -4095.600    4170.543
cylindernumber_five   -5235.5232   2887.214     -1.813      0.072   -1.09e+04     466.990
cylindernumber_four   -3741.3604   3542.130     -1.056      0.292   -1.07e+04    3254.673
cylindernumber_six    -5441.5317   2628.646     -2.070      0.040   -1.06e+04    -249.713
cylindernumber_three   1604.1476   2774.698      0.578      0.564   -3876.137    7084.432
cylindernumber_twelve -8097.1585   3616.336     -2.239      0.027   -1.52e+04    -954.561
cylindernumber_two       37.4715   2092.597      0.018      0.986   -4095.600    4170.543
==============================================================================
Omnibus:                       81.075   Durbin-Watson:                   1.382
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              487.187
Skew:                           1.379   Prob(JB):                    1.62e-106
Kurtosis:                      10.031   Cond. No.                     1.02e+16
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 1.35e-23. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.

In [228]:
predicts_no_avto = df_dummy_2[['wheelbase', 'carlength', 'carwidth', 'curbweight', 'enginesize',
       'boreratio', 'horsepower', 'fueltype_gas',
       'aspiration_turbo', 'carbody_hardtop', 'carbody_hatchback',
       'carbody_sedan', 'carbody_wagon', 'drivewheel_fwd', 'drivewheel_rwd',
       'enginetype_dohcv', 'enginetype_l', 'enginetype_ohc', 'enginetype_ohcf',
       'enginetype_ohcv', 'enginetype_rotor', 'cylindernumber_five',
       'cylindernumber_four', 'cylindernumber_six', 'cylindernumber_three',
       'cylindernumber_twelve', 'cylindernumber_two']]

In [229]:
X2 = sm.add_constant(predicts_no_avto)  # со всеми, кроме марок машин

In [230]:
model_no_avto = sm.OLS(df_dummy_2.price, X2).fit().summary()
print(model_no_avto)

                            OLS Regression Results
==============================================================================
Dep. Variable:                  price   R-squared:                       0.914
Model:                            OLS   Adj. R-squared:                  0.901
Method:                 Least Squares   F-statistic:                     72.32
Date:                Fri, 09 Dec 2022   Prob (F-statistic):           9.86e-81
Time:                        20:41:31   Log-Likelihood:                -1881.6
No. Observations:                 205   AIC:                             3817.
Df Residuals:                     178   BIC:                             3907.
Df Model:                          26
Covariance Type:            nonrobust
=========================================================================================
                            coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------------
const                   -1.7e+04    1.3e+04     -1.309      0.192   -4.26e+04    8625.219
wheelbase                71.1868     87.028      0.818      0.414    -100.552     242.925
carlength               -51.3497     50.341     -1.020      0.309    -150.692      47.993
carwidth                541.8700    253.327      2.139      0.034      41.958    1041.782
curbweight                2.9577      1.796      1.647      0.101      -0.585       6.501
enginesize               36.0515     22.376      1.611      0.109      -8.105      80.208
boreratio             -2230.4519   1731.681     -1.288      0.199   -5647.719    1186.815
horsepower               86.8164     16.717      5.193      0.000      53.827     119.806
fueltype_gas          -2423.0935    975.579     -2.484      0.014   -4348.283    -497.904
aspiration_turbo      -1139.2334    787.230     -1.447      0.150   -2692.738     414.271
carbody_hardtop       -3728.0949   1519.366     -2.454      0.015   -6726.383    -729.807
carbody_hatchback     -4639.1279   1294.594     -3.583      0.000   -7193.855   -2084.401
carbody_sedan         -3337.7854   1356.075     -2.461      0.015   -6013.838    -661.732
carbody_wagon         -4315.4661   1465.089     -2.946      0.004   -7206.646   -1424.287
drivewheel_fwd          297.2402   1121.766      0.265      0.791   -1916.431    2510.912
drivewheel_rwd         1939.1594   1226.536      1.581      0.116    -481.263    4359.582
enginetype_dohcv      -1.713e+04   4540.120     -3.773      0.000   -2.61e+04   -8171.142
enginetype_l           2176.0521   1332.818      1.633      0.104    -454.106    4806.211
enginetype_ohc         4006.5687    897.437      4.464      0.000    2235.584    5777.553
enginetype_ohcf        5421.2822   1388.078      3.906      0.000    2682.076    8160.488
enginetype_ohcv       -5001.2242   1345.435     -3.717      0.000   -7656.280   -2346.169
enginetype_rotor      -5196.6413   2084.532     -2.493      0.014   -9310.217   -1083.066
cylindernumber_five   -1.389e+04   2891.599     -4.802      0.000   -1.96e+04   -8180.353
cylindernumber_four   -1.618e+04   3243.610     -4.989      0.000   -2.26e+04   -9780.800
cylindernumber_six    -1.175e+04   2287.516     -5.135      0.000   -1.63e+04   -7231.547
cylindernumber_three  -9264.0553   4750.899     -1.950      0.053   -1.86e+04     111.279
cylindernumber_twelve -1.214e+04   3386.507     -3.585      0.000   -1.88e+04   -5458.378
cylindernumber_two    -5196.6413   2084.532     -2.493      0.014   -9310.217   -1083.066
==============================================================================
Omnibus:                       18.493   Durbin-Watson:                   1.249
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               50.728
Skew:                           0.293   Prob(JB):                     9.65e-12
Kurtosis:                       5.365   Cond. No.                     1.02e+16
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 1.35e-23. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.

In [ ]:
# Вывод:
# Большинство коэффициентов, связанных с марками машин, статистически незначимы
# Если судить чисто по диагностическим показателям (вроде R2), то модель со всеми предикторами лучшая

In [241]:
#     Заполните пропуски в результатах.

In [ ]:
# Выбранная модель объясняет примерно 90% дисперсии (окр. до целого). Среди предикторов 10 из 27 оказались 
# не значимыми (p > 0.05). Пример интерпретации: при единичном изменении показателя horsepower, цена
# возрастает на 86.8164 (без округления).